{% set name = "pyworkout-toolkit" %}
{% set version = "0.0.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/triskadecaepyon/pyworkout-toolkit/archive/v{{ version }}.tar.gz
  sha256: b9ce8d92ede641d703db1f37df83cef23b073b136d46162294b9f5b1a07c2b58

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy >=1.11
    - pandas >=0.19.0
    - lxml >=4.0.0

test:
  imports:
    - pyworkout

about:
  home: https://github.com/triskadecaepyon/pyworkout-toolkit/
  license: BSD 3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'Python tools to process workout data and telemetry for metrics and machine learning'
  description: |
    The pyworkout-toolkit is a Python package that provides tools for
    post-workout analysis of data or telemetry.  The toolkit provides parsing of
    the popular .TCX and .GPX formats, along with some general purpose functions
    that help preprocess the data for metrics, visualization,
    and machine learning.
  doc_url: https://github.com/triskadecaepyon/pyworkout-toolkit/
  dev_url: https://github.com/triskadecaepyon/pyworkout-toolkit/

extra:
  recipe-maintainers:
    - triskadecaepyon
