travis:
  secure:
    BINSTAR_TOKEN: Dg0ZxutfTzKbYkG/nKT354L2Vk1bDmC1jZ6K8HrTU8e3eb8S1zxYSTFg/FhVB/XT4d9zBNc5cYjZi4fBwkErhiQeWZGKZGgsLmoxjc5t0JDL6FLxAR+rYkBwzlF5NZGV70uAU87D6zmHKlIsvh2R8/EK9KrGApw/ul2FMXEfHYEIgGMdFGVw/fWLF6Pk4jIpCmjtnnSEEv95J1XftXYW7ZaC2s6gLNOW/hbrBAca0G3QSmiemm6GwdfBBWGMHpT3nuyB904ZMBV9wWC6ORXq1GISfRda0Yh/qREk9oyOzm/5iYKJy+OdZMSSq8TYRI11KX90yda7oVAEJLbz42TELwRJV5LPMrHugtFUsF+AKXXJn8CqHyH/gr+FMTj6/h2UFM85lql/+420MPHsIyIswSPVqzFEoF6S06mk2v+p0kOmTW7LID5q50qCPshePJqbVbVIRHb/V7tEUa5apgY2UX8HLZTB/KlHiIyvdHwdBxItPpmtpDeBROnQeE+UGvckSkY5MEcR+dOYn+DVnBSJ+KZdzim3gRF7XISvZ8cw05ps14kecPyv5vxC389hrMLlr7PNC3/dZGmMT7bFjBpBMVIIUEH5o4uw0Vegrj6JKEfSLcSVdqUH1e3tDvY2zIWWmFOaZ0Bo/8ihCs29f+/I+nrIUww58RQB8zpbKNID91E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
